% Table 1 / Q.762 - ISDN user part message acronyms

-define(ISUP_MSGT_ACM).	%  Address complete
-define(ISUP_MSGT_ANM).	%  Answer
-define(ISUP_MSGT_APM).	%  Application transport
-define(ISUP_MSGT_BLA).	%  Blocking acknowledgement
-define(ISUP_MSGT_BLO).	%  Blocking
-define(ISUP_MSGT_CCR).	%  Continuity check request
-define(ISUP_MSGT_CFN).	%  Confusion
-define(ISUP_MSGT_CGB).	%  Circuit group blocking
-define(ISUP_MSGT_CGBA).%  Circuit group blocking acknowledgement
-define(ISUP_MSGT_CGU).	%  Circuit group unblocking
-define(ISUP_MSGT_CGUA).%  Circuit group unblocking acknowledgement
-define(ISUP_MSGT_CON).	%  Connect
-define(ISUP_MSGT_COT).	%  Continuity
-define(ISUP_MSGT_CPG).	%  Call progress
-define(ISUP_MSGT_CRG).	%  Charge information
-define(ISUP_MSGT_CQM).	%  Circuit group query
-define(ISUP_MSGT_CQR).	%  Circuit group query response
-define(ISUP_MSGT_DRS).	%  Delayed release (reserved – used in 1988 version)
-define(ISUP_MSGT_FAA).	%  Facility accepted
-define(ISUP_MSGT_FAC).	%  Facility
-define(ISUP_MSGT_FAR).	%  Facility request
-define(ISUP_MSGT_FOT).	%  Forward transfer
-define(ISUP_MSGT_FRJ).	%  Facility reject
-define(ISUP_MSGT_GRA).	%  Circuit group reset acknowledgement
-define(ISUP_MSGT_GRS).	%  Circuit group reset
-define(ISUP_MSGT_IAM).	%  Initial address
-define(ISUP_MSGT_IDR).	%  Identification request
-define(ISUP_MSGT_IRS).	%  Identification response
-define(ISUP_MSGT_INF).	%  Information
-define(ISUP_MSGT_INR).	%  Information request
-define(ISUP_MSGT_LPA).	%  Loop back acknowledgement
-define(ISUP_MSGT_LOP).	%  Loop prevention
-define(ISUP_MSGT_NRM).	%  Network resource management
-define(ISUP_MSGT_OLM).	%  Overload
-define(ISUP_MSGT_PAM).	%  Pass-along
-define(ISUP_MSGT_PRI).	%  Pre-release information
-define(ISUP_MSGT_REL).	%  Release
-define(ISUP_MSGT_RES).	%  Resume
-define(ISUP_MSGT_RLC).	%  Release complete
-define(ISUP_MSGT_RSC).	%  Reset circuit
-define(ISUP_MSGT_SAM).	%  Subsequent address
-define(ISUP_MSGT_SDM).	%  Subsequent directory number
-define(ISUP_MSGT_SGM).	%  Segmentation
-define(ISUP_MSGT_SUS).	%  Suspend
-define(ISUP_MSGT_UBL).	%  Unblocking
-define(ISUP_MSGT_UBA).	%  Unblocking acknowledgement
-define(ISUP_MSGT_UCIC).%  Unequipped circuit identification code
-define(ISUP_MSGT_UPA).	%  User part available
-define(ISUP_MSGT_UPT).	%  User part test
-define(ISUP_MSGT_USR).	%  User-to-user information

